name: CI

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: ls -a && pwd
      - run: cd packages/jaspurr
      - run: ls -a && pwd
